global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'consul-consumer'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:7071']

  - job_name: 'consul-provider'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:7072']

