server:
  port: 7072

spring:
  application:
    name: provider-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 30s


    openfeign:
      client:
        config:
          consumer-service:
            logger-level: FULL

logging:
  level:
    feign: debug
    org.example.api: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus




