server:
  port: 7071
spring:
  application:
    name: consumer-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        register: true
        health-check-path: /actuator/health
        health-check-interval: 30s

    openfeign:
      client:
        config:
          provider-service: # 服务名称
            logger-level: Full
logging:
  level:
    feign: debug
    org.example.api: debug

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus